# Generated by Django 3.1.4 on 2020-12-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'unique': 'This name already exist'}, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('ph', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('experience', models.IntegerField(default=0)),
                ('hospitalname', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
            ],
        ),
    ]
