# Generated by Django 3.1.4 on 2015-04-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ert',
            name='date',
        ),
        migrations.RemoveField(
            model_name='ert',
            name='district',
        ),
        migrations.RemoveField(
            model_name='ert',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='ert',
            name='hospitalname',
        ),
    ]
